#!/usr/bin/env bash

# Build a go binary in an alpine container, and extract the binary.
# This is useful for a cross-compile step when preparing an alpine image that contains only the go binary.

set -o errexit
set -o nounset
set -o pipefail

LDFLAGS=${LDFLAGS:-}

if [[ $# -ne
RFC 3986                   URI Generic Syntax               2  URI           = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

   hier-part     = "//" authority path-abempty
                 / path-absolute
                 / path-rootless
                 / path-empty

   URI-reference = URI / relative-ref

   absolute-URI  = scheme ":" hier-part [ "?" query ]

   relative-ref  = relative-part [ "?" query ] [ "#" fragment ]

   relative-part = "//" authority path-abempty
                 / path-absolute
                 / path-noscheme
                 / path-empty

   scheme        = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )

   authority     = [ userinfo "@" ] host [ ":" port ]
   userinfo      = *( unreserved / pct-encoded / sub-delims / ":" )
   host          = IP-literal / IPv4address / reg-name
   port          = *DIGIT

   IP-literal    = "[" ( IPv6address / IPvFuture  ) "]"

   IPvFuture     = "v" 1*HEXDIG "." 1*( unreserved / sub-delims / ":" )

   IPv6address   =                            6( h16 ":" ) ls32
                 /                       "::" 5( h16 ":" ) ls32
                 / [               h16 ] "::" 4( h16 ":" ) ls32
                 / [ *1( h16 ":" ) h16 ] "::" 3( h16 ":" ) ls32
                 / [ *2( h16 ":" ) h16 ] "::" 2( h16 ":" ) ls32
                 / [ *3( h16 ":" ) h16 ] "::"    h16 ":"   ls32
                 / [ *4( h16 ":" ) h16 ] "::"              ls32
                 / [ *5( h16 ":" ) h16 ] "::"              h16
                 / [ *6( h16 ":" ) h16 ] "::"

   h16           = 1*4HEXDIG
   ls32          = ( h16 ":" h16 ) / IPv4address
   IPv4address   = dec-octet "." dec-octet "." dec-octet "." dec-octet







Berners-Lee, et al.         Standards Track                    [Page 49]

RFC 3986                   URI Generic Syntax               January 2005


   dec-octet     = DIGIT                 ; 0-9
                 / %x31-39 DIGIT         ; 10-99
                 / "1" 2DIGIT            ; 100-199
                 / "2" %x30-34 DIGIT     ; 200-249
                 / "25" %x30-35          ; 250-255

   reg-name      = *( unreserved / pct-encoded / sub-delims )

   path          = path-abempty    ; begins with "/" or is empty
                 / path-absolute   ; begins with "/" but not "//"
                 / path-noscheme   ; begins with a non-colon segment
                 / path-rootless   ; begins with a segment
                 / path-empty      ; zero characters

   path-abempty  = *( "/" segment )
   path-absolute = "/" [ segment-nz *( "/" segment ) ]
   path-noscheme = segment-nz-nc *( "/" segment )
   path-rootless = segment-nz *( "/" segment )
   path-empty    = 0<pchar>

   segment       = *pchar
   segment-nz    = 1*pchar
   segment-nz-nc = 1*( unreserved / pct-encoded / sub-delims / "@" )
                 ; non-zero-length segment without any colon ":"

   pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

   query         = *( pchar / "/" / "?" )

   fragment      = *( pchar / "/" / "?" )

   pct-encoded   = "%" HEXDIG HEXDIG

   unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
   reserved      = gen-delims / sub-delims
   gen-delims    = ":" / "/" / "?" / "#" / "[" / "]" / "@"
   sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "=" 2 ]]
then
  echo "Usage: $0 <packages> <path to binary build>"
  exit 1
fi

HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Switch to the repo root.
cd "$HERE/.."

PACKAGES="$1"
OUT_PATH="$2"

OUT_DIR=$(dirname "$OUT_PATH")
if [[ ! -d "$OUT_DIR" ]]
then
  echo "Output directory $OUT_DIR does not exist."
  echo "This path must be absolute or relative to the repository root."
  exit 1
fi
if [[ -d "$OUT_PATH" ]]
then
  echo "The output path must be a file to be written."
  echo "The path provided is a directory."
  exit 1
fi

BIN_NAME=$(basename "$OUT_PATH")

echo 'Building'
container_id=$(docker run --detach \
  -v "$PWD":/go/src/github.com/docker/infrakit \
  -w /go/src/github.com/docker/infrakit \
  golang:1.6-alpine \
  go build -ldflags "$LDFLAGS" -o /build/$BIN_NAME $PACKAGES)

exit_code=$(docker wait $container_id)
if [[ "$exit_code" != "0" ]]
then
  echo "Build failed with code $exit_code"
  docker logs $container_id
  docker rm $container_id >/dev/null
  exit 1
fi

echo 'Copying binary'
docker cp $container_id:/build/$BIN_NAME "$OUT_PATH"

docker rm $container_id >/dev/null

echo 'Done'
